import type { Token, TokenSet } from '../core/types'

export interface GenerateOptions {
  /** Override the header comment placed at the top of the generated file. */
  header?: string
}

const DEFAULT_HEADER = [
  '// AUTO-GENERATED by @adamkindberg/tailwind-typed — do not edit by hand.',
  '// Re-run generation (the Vite plugin or `tw-typed generate`) to update.',
  '/* eslint-disable */',
].join('\n')

/** Emit a safely-escaped TS/JS string literal (handles quotes inside font stacks, etc.). */
const lit = (s: string): string => JSON.stringify(s)

/** Stable ordering so regenerating produces identical output (diff-friendly, `--check`-safe). */
function sortTokens(tokens: Token[]): Token[] {
  return [...tokens].sort(
    (a, b) =>
      a.namespace.localeCompare(b.namespace, 'en') ||
      a.key.localeCompare(b.key, 'en', { numeric: true }),
  )
}

/** Generate a self-contained TypeScript module exposing the resolved theme tokens. */
export function generateModule(set: TokenSet, options: GenerateOptions = {}): string {
  const tokens = sortTokens(set.tokens)

  const grouped = new Map<string, Token[]>()
  for (const t of tokens) {
    const arr = grouped.get(t.namespace) ?? []
    arr.push(t)
    grouped.set(t.namespace, arr)
  }

  const out: string[] = [options.header ?? DEFAULT_HEADER, '']

  // --- tokens object ---
  out.push('export const tokens = {')
  for (const [ns, list] of grouped) {
    out.push(`  ${lit(ns)}: {`)
    for (const t of list) {
      out.push(`    ${lit(t.key)}: { var: ${lit(t.var)}, value: ${lit(t.value)} },`)
    }
    out.push('  },')
  }
  out.push('} as const', '')

  // --- core types + accessors ---
  out.push(
    'export type Namespace = keyof typeof tokens',
    'export type TokenKey<N extends Namespace> = keyof (typeof tokens)[N]',
    '',
    'export function cssVar<N extends Namespace>(namespace: N, token: TokenKey<N>): string {',
    '  return (tokens[namespace] as Record<string, { var: string; value: string }>)[token as string].var',
    '}',
    '',
    'export function value<N extends Namespace>(namespace: N, token: TokenKey<N>): string {',
    '  return (tokens[namespace] as Record<string, { var: string; value: string }>)[token as string].value',
    '}',
    '',
  )

  // --- typed class-name builders for color utilities ---
  if (grouped.has('color')) {
    out.push(
      'export type ColorToken = keyof (typeof tokens)["color"]',
      '',
      '/** Typed Tailwind class-name builders for color utilities. */',
      'export const cn = {',
      '  bg: (token: ColorToken): string => `bg-${token}`,',
      '  text: (token: ColorToken): string => `text-${token}`,',
      '  border: (token: ColorToken): string => `border-${token}`,',
      '  ring: (token: ColorToken): string => `ring-${token}`,',
      '  outline: (token: ColorToken): string => `outline-${token}`,',
      '  fill: (token: ColorToken): string => `fill-${token}`,',
      '  stroke: (token: ColorToken): string => `stroke-${token}`,',
      '} as const',
      '',
    )
  }

  // --- iterable token list ---
  out.push(
    'export interface TokenInfo {',
    '  namespace: Namespace',
    '  key: string',
    '  name: string',
    '  var: string',
    '  value: string',
    '  isDefault: boolean',
    '}',
    '',
    'export const allTokens: TokenInfo[] = [',
  )
  for (const t of tokens) {
    out.push(
      `  { namespace: ${lit(t.namespace)}, key: ${lit(t.key)}, name: ${lit(t.name)}, var: ${lit(t.var)}, value: ${lit(t.value)}, isDefault: ${t.isDefault} },`,
    )
  }
  out.push(']', '')

  return out.join('\n')
}
